### PR TITLE
refactor: upgraded frontend-build version to v12

### PR DESCRIPTION
**Pull request by BilalQamar95**
GIT Ticket: [42: Upgrade eslint to v8.x](https://github.com/openedx/frontend-wg/issues/42)

**What changed?**

- Updated `frontend-build `to v12 (Eslint was updated in `frontend-build` version resulting in it's version being bumped to v12. This PR updates `frontend-build` to reciprocate eslint version update)
- Resolved `eslint` issues

### CODE REVIEW

**Review by ansabgillani — APPROVED** [review]

**Comment by mphilbrick211** [comment]
Hi @BilalQamar95! Just checking to see if you intend to proceed with this PR? If so, please note, the branch conflicts must be resolved before review/merge. Thank you!

**Comment by BilalQamar95** [comment]
> Hi @BilalQamar95! Just checking to see if you intend to proceed with this PR? If so, please note, the branch conflicts must be resolved before review/merge. Thank you!

Hi @mphilbrick211, I have updated the PR to latest frontend-build version & resolved subsequent `eslint` issues along with merge conflicts. PR is ready to be reviewed.

**Comment by mphilbrick211** [comment]
Hi @BilalQamar95! Would you mind rebasing to resolve the branch conflicts?

CC: @ansabgillani - this should be ready to merge once the branch item is resovled.

**Comment by BilalQamar95** [comment]
Hi @mphilbrick211, I have resolved the merge conflicts

**Comment by mphilbrick211** [comment]
Hi @BilalQamar95 - looks like more conflicts need to be resolved.

@ansabgillani - flagging for you since this looks like it might be good-to-go once the conflicts are resolved.

**Comment by BilalQamar95** [comment]
Hi @mphilbrick211, I have resolved the merge conflicts

**Comment by mphilbrick211** [comment]
I'm not sure why, but the branch error still says out-of-date @BilalQamar95.

**Comment by BilalQamar95** [comment]
@mphilbrick211 I just updated it from master branch

**Pull request merged**
