### PR TITLE
feat: allow runtime configuration

### PR DESCRIPTION
**Pull request by dcoa**
**Description**

This PR is part of the work to make it possible to configure the frontend applications at runtime (you can referer to this https://github.com/openedx/frontend-wg/issues/103).

**Changes**

 - Update frontend-platform to version 2.5.1
 - Use Helmet library to change the favicon in runtime.
 - Use getConfig() to insert configuration. 

Screenshot 

Values come from runtime configuration 

publisher evidence

**How to test**

- To allow runtime configuration set a new environment variables `MFE_CONFIG_API_URL` and `APP_ID` in the env file and add the api url ( To test this you can use the API from this https://github.com/openedx/edx-platform/pull/30473 or use an external tool to mock the API response).
- The API should respond with a JSON with the config values, something like:
```json
{
  "SITE_NAME": "Test Site",
  "LOGO_URL": "https://testimage.com/logo.svg",
  "LOGO_TRADEMARK_URL": "https://testimage.com/logo.svg",
  "LOGO_WHITE_URL": "https://testimage.com/logo.svg",
  "FAVICON_URL": "https://testimage.com/favicon.ico",
}
```
- The initialize process should work normally.
_Note: You can combine buildtime and runtime configuration_

### CODE REVIEW

**Comment by mphilbrick211** [comment]
@azanbinzahid could you please review and enable tests to run?

**Review by Ali-D-Akbar — APPROVED** [review]
Haven't tested on local but the changes look good.

**Review by ansabgillani — APPROVED** [review]

**Comment by dcoa** [comment]
Thanks, @Ali-D-Akbar  and @ansabgillani for reviewing it.

Let me know if you need more information to merge it. :)

C.C @arbrandes

**Comment by openedx-webhooks** [comment]
@dcoa 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-publisher&entry.867055334=https://github.com/openedx/frontend-app-publisher/pull/786&entry.1484655318=https://github.com/dcoa&entry.752974735=2022-10-18+18:16&entry.1917517419=2022-11-08+06:46&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
