### PR TITLE
refactor: replaced deprecated Paragon form components

### PR DESCRIPTION
**Pull request by abdullahwaheed**
### Ticket
[Migrate off deprecated Paragon components](https://github.com/openedx/frontend-wg/issues/102#)

### What has changed
Updated deprecated `InputText` to `Form.Control` and `InputSelect` to `Form.Control`.

###
**Important**: We have to use ReduxForm validations in place of HTML validations to get proper validation errors provided by Paragon

### CODE REVIEW

**Review by ansabgillani — APPROVED** [review]

**Comment by mphilbrick211** [comment]
Hi @abdullahwaheed! Could you please rebase so we can get this through?

**Comment by arbrandes** [comment]
@abdullahwaheed, looks like the PR is approved, but we need a rebase to resolve conflicts.

**Comment by mphilbrick211** [comment]
Hi @abdullahwaheed! Friendly ping on Adolfo's comment above re: rebasing.

**Comment by abdullahwaheed** [comment]
@arbrandes @mphilbrick211 rebase done with master, please merge this

**Pull request merged**
