### PR TITLE
Moving code coverage from codecov package to CI 

### PR DESCRIPTION
**Pull request by abdullahwaheed**
Codecov NodeJS Uploader [package](https://www.npmjs.com/package/codecov) is depreciated since version 3.8.3

This PR move the coverage to CI according to the new guidelines and [depreciation](https://about.codecov.io/blog/codecov-uploader-deprecation-plan/) plan of codecov

### CODE REVIEW

**Comment by mphilbrick211** [comment]
Hi @abdullahwaheed! You will need to rebase to correct the branch date, then we can review. Thank you!

**Comment by Mashal-m** [comment]
> Hi @abdullahwaheed! You will need to rebase to correct the branch date if you plan to continue with this PR. Thank you!

This pr is outdated, I have created a new PR [#799](https://github.com/openedx/frontend-app-publisher/pull/799) which is why closing this

**Comment by mphilbrick211** [comment]
@Mashal-m @abdullahwaheed just confirming - this PR is OK to close, correct?

**Comment by Mashal-m** [comment]
> @Mashal-m @abdullahwaheed just confirming - this PR is OK to close, correct?

Yes, it is ok to close.

**Comment by abdullahwaheed** [comment]
yes, closing it now as we have a new one

**Pull request closed without merging**
